import express from 'express';
import multer from 'multer';
import ffmpegPath from 'ffmpeg-static';
import { spawn } from 'node:child_process';
import { mkdir, readFile, rm, writeFile } from 'node:fs/promises';
import path from 'node:path';
import crypto from 'node:crypto';
import { fileURLToPath } from 'node:url';
const root=path.dirname(fileURLToPath(import.meta.url)),jobsRoot=path.join(root,'jobs');await mkdir(jobsRoot,{recursive:true});
const app=express(),upload=multer({dest:jobsRoot,limits:{fileSize:1024*1024*1024,files:101}});app.use(express.static(path.join(root,'dist')));
function run(args){return new Promise((resolve,reject)=>{const child=spawn(ffmpegPath,args,{windowsHide:true});let error='';child.stderr.on('data',c=>{error+=c.toString();if(error.length>12000)error=error.slice(-12000)});child.on('error',reject);child.on('close',code=>code===0?resolve():reject(new Error(error||`FFmpeg exited ${code}`)))})}
app.post('/api/render',upload.fields([{name:'voice',maxCount:1},{name:'media',maxCount:100}]),async(req,res)=>{const dir=path.join(jobsRoot,crypto.randomUUID());await mkdir(dir,{recursive:true});try{const voice=req.files?.voice?.[0],media=req.files?.media||[],scenes=JSON.parse(req.body.scenes||'[]');if(!voice||!media.length||!scenes.length)return res.status(400).json({error:'Thiếu voice, tư liệu hoặc timeline.'});const segments=[];for(let i=0;i<scenes.length;i++){const scene=scenes[i],source=media[scene.mediaIndex]?.path;if(!source)throw new Error(`Không tìm thấy tư liệu cho cảnh ${i+1}`);const out=path.join(dir,`scene-${String(i).padStart(4,'0')}.mp4`),duration=Math.max(.5,Number(scene.end)-Number(scene.start)),common=['-y','-hide_banner','-loglevel','error'],vf='scale=1920:1080:force_original_aspect_ratio=decrease,pad=1920:1080:(ow-iw)/2:(oh-ih)/2,setsar=1,fps=30,format=yuv420p';if(scene.mediaType==='image')await run([...common,'-loop','1','-i',source,'-t',String(duration),'-vf',vf,'-an','-c:v','libx264','-preset','veryfast',out]);else await run([...common,'-stream_loop','-1','-i',source,'-t',String(duration),'-vf',vf,'-an','-c:v','libx264','-preset','veryfast',out]);segments.push(out)}const concatFile=path.join(dir,'concat.txt');await writeFile(concatFile,segments.map(f=>`file '${f.replaceAll("'","'\\''")}'`).join('\n'));const joined=path.join(dir,'joined.mp4');await run(['-y','-hide_banner','-loglevel','error','-f','concat','-safe','0','-i',concatFile,'-c','copy',joined]);const output=path.join(dir,'matchcut-output.mp4');await run(['-y','-hide_banner','-loglevel','error','-i',joined,'-i',voice.path,'-map','0:v:0','-map','1:a:0','-c:v','copy','-c:a','aac','-b:a','192k','-shortest','-movflags','+faststart',output]);const buffer=await readFile(output);res.setHeader('Content-Type','video/mp4');res.setHeader('Content-Disposition','attachment; filename="matchcut-output.mp4"');res.send(buffer)}catch(error){res.status(500).json({error:error instanceof Error?error.message.split('\n').slice(-4).join(' '):'Không thể render video.'})}finally{setTimeout(()=>void rm(dir,{recursive:true,force:true}),30000)}});
app.get('/api/health',(_req,res)=>res.json({ok:true,engine:'FFmpeg'}));app.listen(4173,()=>console.log('MatchCut FFmpeg: http://localhost:4173'));
